### PR TITLE
fix server creation behavior

### LINKED ISSUE #1: #createServer params
Here https://github.com/ekristen/prometheus-client/blob/master/lib/client.js#L79 the create server function accepts the `listen` parameter. 
On the documentation, create server is called with a port 
```
client.createServer(9090)
```
But that port will not be used. Right?

### PR DESCRIPTION
**Pull request by revington**
fixes #1

It also ads the `#listen` function. Similar to express api.

### CODE REVIEW

**Comment by ekristen** [comment]
Appreciate the PR, can you rebase this?  This will also require a major version bump.

**Comment by revington** [comment]
Done

**Comment by ekristen** [comment]
@revington just thinking about this a little more, since the createServer function is returning an http.createServer instance, I don't think we need the `Client.prototype.listen` function because you can just create the server instance and chain listen on it like you would any other http service anywhere else in Node.

**Comment by revington** [comment]
Of course listen is not needed. The idea was to expose it as a convenient method like the one express exposes http://expressjs.com/en/4x/api.html#app.listen. If you do not like it I can remove it.

**Pull request merged**
